FROM mcr.microsoft.com/dotnet/aspnet:7.0-alpine AS base
WORKDIR /src
EXPOSE 5000

FROM mcr.microsoft.com/dotnet/sdk:7.0-alpine AS build

WORKDIR /src
COPY ["./nuget.config", "./nuget.config"]
COPY ["DailyS.API/DailyS.API.csproj", "DailyS.API/"]
COPY ["DailyS.Domain/DailyS.Domain.csproj", "DailyS.Domain/"]
COPY ["DailyS.Infrastructure/DailyS.Infrastructure.csproj", ".DailyS.Infrastructure/"]
COPY ["DailyS.Persistence/DailyS.Persistence.csproj", "DailyS.Persistence/"]
COPY ["DailyS.Application/DailyS.Application.csproj", "DailyS.Application/"]
COPY ["DailyS.Identity/DailyS.Identity.csproj", "DailyS.Identity/"]
RUN dotnet restore "DailyS.API/DailyS.API.csproj"

COPY . .
WORKDIR "/src/DailyS.API"
RUN dotnet build "DailyS.API.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "DailyS.API.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .

ENTRYPOINT ["dotnet", "DailyS.API.dll"]



